API_KEY = "YYYiM7DuvzINADCosx"
API_SECRET = "j3V4agrapGkqLSQsb75shiSWCTZe8a3TYnDdp"
TELEGRAM_TOKEN = "7863509137:AAHBuRbtzMAOM_yBbVZASfx-oORubvQYxY8"
ALLOWED_USER_ID = 658712542

TAKE_PROFIT_PERCENT = 10  # هدف الربح 10%
STOP_LOSS_PERCENT = 5     # وقف الخسارة 5%
RISK_PER_TRADE = 0.2      # نسبة الدخول من الرصيد 20%
TRADE_SYMBOLS = ["BTCUSDT", "ETHUSDT", "SOLUSDT", "ADAUSDT"]
